"""
Indicators 모듈
기술적 지표 계산
"""

from .moving_average import (
    calculate_sma,
    calculate_ema,
    calculate_wma,
    calculate_all_ma,
    get_ma_values,
    get_ma_status,
    detect_golden_cross,
    detect_dead_cross,
    detect_all_crosses,
    calculate_ma_divergence,
    is_price_above_ma,
    is_price_below_ma,
    get_ma_support_resistance,
    check_ma_alignment,
)

from .volume import (
    calculate_volume_ma,
    calculate_volume_ratio,
    calculate_volume_change,
    detect_volume_spike,
    detect_volume_decline,
    is_accumulation_phase,
    detect_breakout_volume,
    detect_climax_volume,
    calculate_obv,
    calculate_vwap,
    get_volume_profile,
    analyze_volume_trend,
    calculate_volume_indicators,
)

from .candle_pattern import (
    calculate_candle_body,
    calculate_candle_body_ratio,
    calculate_upper_shadow,
    calculate_lower_shadow,
    calculate_candle_range,
    calculate_change_rate,
    is_bullish,
    is_bearish,
    detect_long_bullish_candle,
    detect_long_bearish_candle,
    detect_doji,
    detect_hammer,
    detect_inverted_hammer,
    detect_spinning_top,
    detect_engulfing_bullish,
    detect_engulfing_bearish,
    detect_morning_star,
    detect_evening_star,
    get_candle_support_level,
    get_candle_resistance_level,
    get_candle_50_percent_level,
    analyze_candle_patterns,
    get_pattern_signal,
)

from .support_resistance import (
    calculate_pivot_points,
    find_local_minima,
    find_local_maxima,
    find_support_levels,
    find_resistance_levels,
    is_near_support,
    is_near_resistance,
    get_nearest_support,
    get_nearest_resistance,
    detect_support_break,
    detect_resistance_break,
    find_box_range,
    is_in_box_range,
    detect_box_breakout,
    detect_box_breakdown,
    get_52week_high,
    get_52week_low,
    is_near_52week_high,
    is_52week_high_breakout,
    analyze_support_resistance,
)

__all__ = [
    # moving_average
    'calculate_sma',
    'calculate_ema',
    'calculate_wma',
    'calculate_all_ma',
    'get_ma_values',
    'get_ma_status',
    'detect_golden_cross',
    'detect_dead_cross',
    'detect_all_crosses',
    'calculate_ma_divergence',
    'is_price_above_ma',
    'is_price_below_ma',
    'get_ma_support_resistance',
    'check_ma_alignment',
    # volume
    'calculate_volume_ma',
    'calculate_volume_ratio',
    'calculate_volume_change',
    'detect_volume_spike',
    'detect_volume_decline',
    'is_accumulation_phase',
    'detect_breakout_volume',
    'detect_climax_volume',
    'calculate_obv',
    'calculate_vwap',
    'get_volume_profile',
    'analyze_volume_trend',
    'calculate_volume_indicators',
    # candle_pattern
    'calculate_candle_body',
    'calculate_candle_body_ratio',
    'calculate_upper_shadow',
    'calculate_lower_shadow',
    'calculate_candle_range',
    'calculate_change_rate',
    'is_bullish',
    'is_bearish',
    'detect_long_bullish_candle',
    'detect_long_bearish_candle',
    'detect_doji',
    'detect_hammer',
    'detect_inverted_hammer',
    'detect_spinning_top',
    'detect_engulfing_bullish',
    'detect_engulfing_bearish',
    'detect_morning_star',
    'detect_evening_star',
    'get_candle_support_level',
    'get_candle_resistance_level',
    'get_candle_50_percent_level',
    'analyze_candle_patterns',
    'get_pattern_signal',
    # support_resistance
    'calculate_pivot_points',
    'find_local_minima',
    'find_local_maxima',
    'find_support_levels',
    'find_resistance_levels',
    'is_near_support',
    'is_near_resistance',
    'get_nearest_support',
    'get_nearest_resistance',
    'detect_support_break',
    'detect_resistance_break',
    'find_box_range',
    'is_in_box_range',
    'detect_box_breakout',
    'detect_box_breakdown',
    'get_52week_high',
    'get_52week_low',
    'is_near_52week_high',
    'is_52week_high_breakout',
    'analyze_support_resistance',
]
